using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Frontenac.Blueprints.Util.Wrappers.Event.Listener
{
    /// <summary>
    /// An event generated by changes to the graph.
    /// </summary>
    public interface Event
    {
        void fireEvent(IEnumerator<GraphChangedListener> eventListeners);
    }
}
