using System.Collections.Generic;
using System.Diagnostics.Contracts;

namespace Frontenac.Blueprints.Util.Wrappers.Event.Listener
{
    /// <summary>
    ///     An event generated by changes to the graph.
    /// </summary>
    [ContractClass(typeof (EventContract))]
    public interface IEvent
    {
        void FireEvent(IEnumerator<IGraphChangedListener> eventListeners);
    }
}